name: pitchclass_cnn

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.7.*
  - pip=19.2.*
  - numpy=1.17.*
  - scipy=1.3.*
  - matplotlib=3.1.*
  - ipython=7.8.*
  - jupyter=1.0.*
  - pandas=1.0.*
  - scikit-learn=0.21.*
  - ffmpeg=2.8.*
  - numba=0.45.*
  - jupyter_contrib_nbextensions=0.5.*
  - cython=0.29.*
  - scikit-image=0.15.*
  - Fabric3=1.14.*
  - gitpython=3.0.*
  - tqdm=4.36.*
  - jinja2=2.10.*
  - joblib=0.14.*
  - cudatoolkit=10.0.*
  - cudnn=7.6.*
  - pip:
    - mir-eval==0.5.*
    - nbstripout==0.3.*
    - music21==5.7.*
    - pretty_midi==0.2.*
    - librosa==0.8.*
    - pysoundfile==0.9.*
    - opencv-python==4.1.*
    - tensorflow-gpu==2.0.*
    - tensorflow-probability==0.8.*
    - vamp==1.1.*
